In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds


In [ ]:
tfds.load('gap')

In [ ]:
def convert_examples(x):
    return x

gap = tfds.builder('gap')
gap_test = gap.as_dataset(split='test')
gap_test = gap_test.map(map_func=lambda x: convert_examples(x))
gap_test = gap_test.batch(1)
n_batches = gap.info.splits['test'].num_examples / 1

In [ ]:

def tokeizer(string):
    return string.split()

for x in gap_test:
    print(x['Pronoun-offset'][0])
    print(x['Pronoun'])
    print(x['A'][0], x['A-coref'][0])
    print(x['B'][0], x['B-coref'][0])
    sentence = x['Text'][0].numpy().decode('utf-8')
    char_offset = x['Pronoun-offset'][0].numpy()
    token_offset = offset_char2token(sentence, char_offset, tokeizer)
    tokenized_sentence = tokeizer(sentence)
    print(tokenized_sentence[token_offset])


    break

In [ ]:
def offset_char2token(input_str, char_offset, tokenizer_fn):
    str_part1 = input_str[:char_offset]
    
    tokens_in_part1 = tokenizer_fn(str_part1)
    
    return len(tokens_in_part1)

In [2]:
tfds.load('blimp/anaphor_gender_agreement')

/home/samira/anaconda3/envs/indist/lib/python3.7/site-packages/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,


Shuffling and writing examples to /home/samira/tensorflow_datasets/blimp/anaphor_gender_agreement/0.1.0.incomplete21NICK/blimp-train.tfrecord


Dataset blimp downloaded and prepared to /home/samira/tensorflow_datasets/blimp/anaphor_gender_agreement/0.1.0. Subsequent calls will reuse this data.


{'train': <PrefetchDataset shapes: {UID: (), field: (), lexically_identical: (), linguistics_term: (), one_prefix_method: (), pair_id: (), sentence_bad: (), sentence_good: (), simple_LM_method: (), two_prefix_method: ()}, types: {UID: tf.string, field: tf.string, lexically_identical: tf.bool, linguistics_term: tf.string, one_prefix_method: tf.bool, pair_id: tf.int32, sentence_bad: tf.string, sentence_good: tf.string, simple_LM_method: tf.bool, two_prefix_method: tf.bool}>}

In [7]:
def convert_blimp_examples(x):
    return x

blimp = tfds.builder('blimp/anaphor_gender_agreement')
blimp_test = blimp.as_dataset(split='train')
blimp_test = blimp_test.map(map_func=lambda x: convert_blimp_examples(x))
blimp_test = blimp_test.batch(1)
n_batches = blimp.info.splits['train'].num_examples / 1
print(n_batches)

1000.0


In [13]:
for x in blimp_test:
    print(x['sentence_bad'])
    print(x['sentence_good'])
    

tf.Tensor([b"Michelle shouldn't investigate himself."], shape=(1,), dtype=string)
tf.Tensor([b"Michelle shouldn't investigate herself."], shape=(1,), dtype=string)
tf.Tensor([b'Kayla thinks about itself.'], shape=(1,), dtype=string)
tf.Tensor([b'Kayla thinks about herself.'], shape=(1,), dtype=string)
tf.Tensor([b"Janice hadn't shocked itself."], shape=(1,), dtype=string)
tf.Tensor([b"Janice hadn't shocked herself."], shape=(1,), dtype=string)
tf.Tensor([b'Kendra flees from himself.'], shape=(1,), dtype=string)
tf.Tensor([b'Kendra flees from herself.'], shape=(1,), dtype=string)
tf.Tensor([b"Kenneth wasn't admiring itself."], shape=(1,), dtype=string)
tf.Tensor([b"Kenneth wasn't admiring himself."], shape=(1,), dtype=string)
tf.Tensor([b'Rachelle praises itself.'], shape=(1,), dtype=string)
tf.Tensor([b'Rachelle praises herself.'], shape=(1,), dtype=string)
tf.Tensor([b"Valerie isn't disgusting himself."], shape=(1,), dtype=string)
tf.Tensor([b"Valerie isn't disgusting herself."], shap

In [12]:
print(x)

{'UID': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'anaphor_gender_agreement'], dtype=object)>, 'field': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'morphology'], dtype=object)>, 'lexically_identical': <tf.Tensor: shape=(1,), dtype=bool, numpy=array([False])>, 'linguistics_term': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'anaphor_agreement'], dtype=object)>, 'one_prefix_method': <tf.Tensor: shape=(1,), dtype=bool, numpy=array([ True])>, 'pair_id': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([947], dtype=int32)>, 'sentence_bad': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b"Michelle shouldn't investigate himself."], dtype=object)>, 'sentence_good': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b"Michelle shouldn't investigate herself."], dtype=object)>, 'simple_LM_method': <tf.Tensor: shape=(1,), dtype=bool, numpy=array([ True])>, 'two_prefix_method': <tf.Tensor: shape=(1,), dtype=bool, numpy=array([False])>}
